# Правила для SQL

whitespace = #'\\s+'
identifier = #'[a-zA-Z]+'

A = "a" | "A"
B = "b" | "B"
C = "c" | "C"
#D
E = "e" | "E"
F = "f" | "F"
#G
#H
#I
#J
K = "k" | "K"
L = "l" | "L"
M = "m" | "M"
#N
O = "o" | "O"
#Q
R = "r" | "R"
S = "s" | "S"
T = "t" | "T"
#U
#V
#W
#X
#Y
#Z


