(* Правила для SQL *)
query = select <whitespace> from
select = <select-kw> <whitespace> all
from = <from-kw> <whitespace> table

select-kw = 'select'
from-kw = 'from'

all = '*'
table = identifier

whitespace = #'\s+'
identifier = #'[a-zA-Z]+'
