(* Правила для SQL *)
query = select <whitespace> from
select = <select-kw> <whitespace> (all | select-part (table-dot select-part)* )
from = <from-kw> <whitespace> table
table = table-name (<whitespace> table-alias)?

select-part = (table-alias <column-dot> all) | (table-alias <column-dot> column-name)
select-kw = 'select'
from-kw = 'from'
column-name = identifier

all = '*'
table-name = identifier
table-alias = identifier

column-dot = <'.'>
table-dot = <','>

whitespace = #'\s+'
identifier = #'[a-zA-Z]+'
