(* Правила для SQL *)
query = select <whitespace> from
select = <select-kw> <whitespace> (all | (select-part)?)
from = <from-kw> <whitespace> table
table = table-name (<whitespace> table-alias)?

select-part = table-alias <'.'> all
select-kw = 'select'
from-kw = 'from'

all = '*'
table-name = identifier
table-alias = identifier

whitespace = #'\s+'
identifier = #'[a-zA-Z]+'
